[package]
name = "murating-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
unicode-normalization = "0.1"
caseless = "0.2"
ureq = { version = "2", features = ["gzip"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.55"

[[bin]]
name = "murating-writeslot"
path = "src/bin/writeslot.rs"

[[bin]]
name = "murating-replayslot"
path = "src/bin/replayslot.rs"
